---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        #image: quay.io/stefanprodan/podinfo:3.0.0
        image: nginx:1.14.2 
        ports:
        - containerPort: 3000
