---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
<<<<<<< HEAD
  replicas: 3
=======
  replicas: 2
>>>>>>> 61324fc4b8c1e7cc5adcfc1ba99c9ea85671115d
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: nginx:1.14.2 
        ports:
        - containerPort: 3000
