---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
<<<<<<< HEAD
  replicas: 3
=======
  replicas: 1
>>>>>>> e56acdcd5f61ada0166bbfa47d4f76dfc20fc6f2
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: nginx:1.14.2 
        ports:
        - containerPort: 3000
